# -*- Makefile -*-
#
# Copyright (c) 2003 CNRS/LAAS
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# $LAAS$
#
include  ../../../Init.make
include  ../../../Init.make.vxworks
include  ../../../Init.make.$(TARGET)

#------------------------------------------------------------------------
#   WHAT
#------------------------------------------------------------------------

DIRGENOM = $(ROOTROBOTS)/genom/include

CPPFLAGS += -I$(DIRGENOM) -I$(H2UNIX)/include

WRITE_OBJ = $(TARGET)/testPosterWrite.o
WRITE_SRC = testPosterWrite.c

READ_OBJ = $(TARGET)/testPosterRead.o
READ_SRC = testPosterRead.c


TEST_LIB = $(TARGET)/testPosterLib.o
TEST_LIB_SRC = testPosterLib.c

all: $(WRITE_OBJ) $(READ_OBJ) $(TEST_LIB)

#------------------------------------------------------------------------
#   HOW
#------------------------------------------------------------------------


$(TARGET)/%.o:	%.c
	$(CC) -c  -o $@ $(CPPFLAGS) $(CFLAGS) $<

clean:
	\rm -r $(TARGET)/*

MKDEPFLAGS = -sROOTH2=$(ROOTH2) -k 
depend $(TARGET)/DEPENDANCES.vxworks:: $(WRITE_SRC) $(READ_SRC) $(TEST_LIB_SRC)
	@mkdir -p $(TARGET)
	$(MKDEP) $(MKDEPFLAGS) -i$(DIRVXH) -c$(CC) -o$(TARGET)/DEPENDANCES.vxworks -d$(TARGET) $(CPPFLAGS) $?

include $(TARGET)/DEPENDANCES.vxworks

