# -*- Makefile -*-
#
# Copyright (c) 2000, 2003 CNRS/LAAS
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# $LAAS$
#

include ../../../Init.make

CPPFLAGS += -I../../..
#----------------------------------------------------------------------
# Test programs
TESTR = $(TARGET)/testRead
TESTW = $(TARGET)/testWrite

all: $(TESTR) $(TESTW)

$(TESTR): testRead.c 
	$(CC) -o $(TESTR) $(LDFLAGS) $(CPPFLAGS) $(CFLAGS) testRead.c $(LIBS)

$(TESTW): testWrite.c
	$(CC) -o $(TESTW) $(LDFLAGS) $(CPPFLAGS) $(CFLAGS) testWrite.c $(LIBS)

$(TARGET)/%.o : %.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) $<

depend $(TARGET)/DEPENDANCES:: $(TARGET)

depend $(TARGET)/DEPENDANCES:: testRead.c testWrite.c
	$(MKDEP) -c$(CC) -o$(TARGET)/DEPENDANCES -d'$$(TARGET)' \
	-s H2UNIX=$(H2UNIX) $(CPPFLAGS) $?

$(TARGET):
	-mkdir -p $@

clean:
	rm -f  $(TESTW) $(TESTR) 

install:
	@echo "Nothing to do"

include $(TARGET)/DEPENDANCES

