.\" $Id$
.TH h2devFree 3 "January 1999"
.SH NAME
h2devFree \- free a 
.SM comLib
device
.SH SYNOPSIS
.nf
.B "#include <h2Lib.h>"
.B "#include <h2devLib.h>"
.B "void h2devFree(int dev)"
.fi
.SH DESCRIPTION
.IR h2devFree
frees a 
.SM comLib
device.
The corresponding device is returned to the system.
.SH "SEE ALSO"
.IR h2devAlloc(3)
