.\" $Id$
.TH h2devAlloc 3 "January 1999"
.SH NAME
h2devAlloc \- allocates a 
.SM comLib 
device
.SH SYNOPSIS
.nf
.B "#include <h2Lib.h>"
.B "#include <h2devLib.h>"
.B "int h2devAlloc(char *name, H2_DEV_TYPE type)"
.fi
.SH DESCRIPTION
.IR h2devAlloc
allocates a
.SM comLib
device.
The 
.I name
parameter specifies a name for the device to be allocated, and the 
.I type
parameter specifies the type of the device. It can be
.IR H2_DEV_TYPE_SEM 
to create a semaphore device,
.IR H2_DEV_TYPE_TASK
to create a task device,
.IR H2_DEV_TYPE_MBOX
to create a mailbox device or
.IR H2_DEV_TYPE_POSTER
to create a poster device.
.SH "RETURN VALUE"
.IR h2devAlloc
returns the index of the newly allocated device upon success, or
.IR ERROR
in case of an error. In this case it calls
.IR errnoSet(3)
with the corresponding Unix or comLib error code.
.SH "SEE ALSO"
.IR h2devFree(3) , 
.IR h2devFind(3) ,
.IR h2devShow(3)
