.\" $Id$
.TH h2devShow 3 "January 1999"
.SH NAME
h2devShow \- display a list of 
.SM comLib
devices
.SH SYNOPSIS
.nf
.B "#include <h2Lib.h>"
.B "#include <h2devLib.h>"
.B "void h2devInit(void)"
.fi
.SH DESCRIPTION
.IR h2devShow
outputs to stdout a list of currently allocated 
.SM comLib
devices.
.SH "SEE ALSO"
.IR h2devAlloc(3) ,
.IR h2devFind(3) ,
.IR h2devFree(3)
