.\" Copyright (c) 1999, 2005 CNRS/LAAS
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd January 21, 2005
.Dt osInit 3
.Os pocoLibs
.Sh NAME 
.Nm osInit
.Nd Initialize the portLib part of pocoLibs
.Sh SYNOPSIS
.Fd "#include <portLib.h>"
.Ft STATUS 
.Fn osInit "int clkRate"
.Sh DESCRIPTION
.Fn osInit
initializes the real-time OS library. It should be called one before
any call to other functions of the library. The 
.Fa clkRate
parameter specifies the clock rate used in this process. A value of 
.Dv 0
disable the clock. The maximum value on most systems is the 
.Dv HZ
constant, which is generally equal to 100. 
.Sh RETURN VALUE
.Fn osInit
returns 
.Dv OK
or 
.Dv ERROR
in case of an error. Then it sets the 
.Fa errno
value of the task.
.Sh SEE ALSO
.Xr h2devLib 3
