.\" $Id$
.TH semCCreate 3 "May 1999"
.SH NAME
semCCreate \- create a counting semaphore
.SH SYNOPSIS
.nf
.B "#include <h2Lib.h>"
.B "#include <semLib.h>"
.B "SEM_ID semCCreate(int options, int value)"
.fi
.SH DESCRIPTION
.IR semCCreate 
creates a counting semaphore, that is local to the process creating it.
.I options
can be
.IR SEM_Q_FIFO
to specify that tasks waiting on the semaphore are dequeued in a FIFO
order, or 
.IR SEM_Q_PRIORITY
to specify that tasks waiting on the semaphore are dequeued by
decreasing priority.
.PP
.I value
indicates the initial value of the semaphore.
.SH "RETURN VALUE"
.IR semCCreate
returns the semaphore identifier for the newly created semaphore or
NULL in case of an error. In that case an error code is left in the
task's errno value. 
.SH "SEE ALSO"
.IR semCCreate(3) ,
.IR semTake(3) ,
.IR semGive(3) ,
.IR semDelete(3)
