#!/bin/csh -f
#
# Copyright (c) 1992-2003 CNRS/LAAS
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
set pid_file = /tmp/xes-pid
set host = `uname -n`
set me = `whoami`
#
# Verifie l'existence du fichier
if ( ! -f $pid_file ) then
	echo "kill_xes: il ne semble pas y avoir de xes_server sur ${host}"
	exit 0
endif
#
# Verifie le proprietaire du fichier
set owner=`ls -l $pid_file | awk '{print $3}'`
if ( "${me}" != "root" && "${owner}" != "${me}" ) then
	echo "kill_xes: le processus xes_server appartient à ${owner}"
	exit -1
endif
#
# Tue le process xes_server
kill `cat $pid_file`
#
# Nettoie le fichier
rm  -f ${pid_file}
exit 0
