#!/bin/csh -f
# 
# Script pour tuer un process xes_server
#
# Matthieu Herrb - Avril 1994
#
# Copyright (C) 1994 LAAS/CNRS
#
# $Id$
#
set pid_file = /tmp/xes-pid
set host = `uname -n`
set me = `whoami`
#
# Verifie l'existence du fichier
if ( ! -f $pid_file ) then
	echo "kill_xes: il ne semble pas y avoir de xes_server sur ${host}"
	exit 0
endif
#
# Verifie le proprietaire du fichier
set owner=`ls -l $pid_file | awk '{print $3}'`
if ( "${me}" != "root" && "${owner}" != "${me}" ) then
	echo "kill_xes: le processus xes_server appartient à ${owner}"
	exit -1
endif
#
# Tue le process xes_server
kill `cat $pid_file`
#
# Nettoie le fichier
rm  -f ${pid_file}
exit 0
