/* DO NOT EDIT THIS FILE BY HAND (use h2addErrno) */

/*
 * List of the sources of errors
 *
 * H2 modules errors
 * -----------------
 * From auto/ndError.h:
 *	9033, ndExecTask
 *	9032, ndPosterLib
 *	9031, ndMsgLib
 *	9030, ndCntrlTask
 * From /home/bmorisse/robots/nomadic/modules/UGrid-nomadic/auto/UGridError.h:
 *	9013, UGridMatriceFixeTask
 *	9012, UGridPosterLib
 *	9011, UGridMsgLib
 *	9010, UGridCntrlTask
 * From /usr/local/robots/nomadic/modules/inter/auto/interError.h:
 *	9004, interWriteRef
 *	9003, interInterExecTask
 *	9002, interPosterLib
 *	9001, interMsgLib
 *	9000, interCntrlTask
 * From /home/bmorisse/robots/nomadic/modules/stat/auto/statError.h:
 *	5026, statstatExecTask
 *	5025, statPosterLib
 *	5024, statMsgLib
 *	5023, statCntrlTask
 * From auto/xr4000Error.h:
 *	3624, xr4000ExecTask
 *	3623, xr4000PumpTask
 *	3622, xr4000PosterLib
 *	3621, xr4000MsgLib
 *	3620, xr4000CntrlTask
 * From auto/m2dError.h:
 *	3613, m2dCmd
 *	3612, m2dPosterLib
 *	3611, m2dMsgLib
 *	3610, m2dCntrlTask
 * From /usr/local/robots/nomadic/band/band.h:
 *	3605, bandLib
 * From /usr/local/robots/nomadic/modules/band/auto/bandError.h:
 *	3603, bandExecTask
 *	3602, bandPosterLib
 *	3601, bandMsgLib
 *	3600, bandCntrlTask
 * From /usr/local/robots/nomadic/modules/sick/auto/sickError.h:
 *	3503, sickScanTask
 *	3502, sickPosterLib
 *	3501, sickMsgLib
 *	3500, sickCntrlTask
 * From /home/matthieu/robots/nomadic/modules/segloc/auto/seglocError.h:
 *	3333, seglocCmdTask
 *	3332, seglocPosterLib
 *	3331, seglocMsgLib
 *	3330, seglocCntrlTask
 * From /usr/local/robots/nomadic/modules/platine/auto/platineError.h:
 *	3034, platineGetPosTask
 *	3033, platineCmdTask
 *	3032, platinePosterLib
 *	3031, platineMsgLib
 *	3030, platineCntrlTask
 *
 * H2 hardLib errors
 * -----------------
 *
 * H2 comLib errors
 * -----------------
 * From /usr/local/robots/posix/include/remotePosterLib.h:
 *	516, remotePosterLib
 * From csLib.h:
 *	512, csLib
 * From /usr/local/robots/posix/include/gcomLib.h:
 *	511, gcomLib
 * From /usr/local/robots/posix/include/posterLib.h:
 *	510, posterLib
 * From mboxLib.h:
 *	508, mboxLib
 * From h2evnLib.h:
 *	507, h2evnLib
 * From commonStructLib.h:
 *	506, commonStructLib
 * From h2devLib.h:
 *	505, h2devLib
 * From h2timerLib.h:
 *	504, h2timerLib
 * From h2semLib.h:
 *	503, h2semLib
 * From h2rngLib.h:
 *	501, h2rngLib
 *
 * System errors
 * -----------------
 * From smObjLib.h:
 *	72, smObjLib
 * From objLib.h:
 *	61, objLib
 * From tickLib.h:
 *	60, tickLib
 * From wdLib.h:
 *	34, wdLib
 * From symLib.h:
 *	28, symLib
 * From semLib.h:
 *	22, semLib
 * From memLib.h:
 *	17, memLib
 */


/*
 * Arrays of errors for each source
 * (error name, error number)
 */

static H2_FAILED_STRUCT _U_GRID_CNTRL_TASK_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/UGrid-nomadic/auto/UGridError.h */
	{"S_UGridCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_UGridCntrlTask_ACTIVITY_FAILED", 2},
	{"S_UGridCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_UGridCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_UGridCntrlTask_SYSTEM_ERROR", 6},
	{"S_UGridCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_UGridCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_UGridCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_UGridCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT _U_GRID_MATRICE_FIXE_TASK_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/UGrid-nomadic/auto/UGridError.h */
	{"S_UGridMatriceFixeTask_MODE_UNKNOWN", 10},
	{"S_UGridMatriceFixeTask_POSTER_ADDR_FAILED", 15},
	{"S_UGridMatriceFixeTask_POSTER_FIND_FAILED", 14},
	{"S_UGridMatriceFixeTask_POSTER_INIT_FAILED", 13},
	{"S_UGridMatriceFixeTask_POSTER_NOT_FOUND", 11},
	{"S_UGridMatriceFixeTask_POSTER_READ_FAILED", 12},
};

static H2_FAILED_STRUCT _U_GRID_MSG_LIB_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/UGrid-nomadic/auto/UGridError.h */
	{"S_UGridMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT BAND_CNTRL_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/band/auto/bandError.h */
	{"S_bandCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_bandCntrlTask_ACTIVITY_FAILED", 2},
	{"S_bandCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_bandCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_bandCntrlTask_SYSTEM_ERROR", 6},
	{"S_bandCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_bandCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_bandCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_bandCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT BAND_EXEC_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/band/auto/bandError.h */
	{"S_bandExecTask_BAD_PARAMETERS", 17},
	{"S_bandExecTask_BAD_TRAJ_TYPE", 14},
	{"S_bandExecTask_COLLISION_DETECTED", 10},
	{"S_bandExecTask_INVALID_STATE", 16},
	{"S_bandExecTask_POSTER_NOT_FOUND", 15},
	{"S_bandExecTask_POSTER_READ_ERROR", 13},
	{"S_bandExecTask_TRAJ_IN_COLLISION", 11},
	{"S_bandExecTask_TRAJ_NOT_CONNECTED", 12},
};

static H2_FAILED_STRUCT BAND_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/band/band.h */
	{"S_bandLib_SEGMENTS_NOT_UPDATED", 0},
};

static H2_FAILED_STRUCT BAND_MSG_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/band/auto/bandError.h */
	{"S_bandMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT COMMON_STRUCT_LIB_TAB_FAIL[]= {
 /* From commonStructLib.h */
	{"S_commonStructLib_ISNT_COMMON_STRUCT", 0},
};

static H2_FAILED_STRUCT CS_LIB_TAB_FAIL[]= {
 /* From csLib.h */
	{"S_csLib_BAD_BLOCK_TYPE", 7},
	{"S_csLib_BAD_INTERMED_FLAG", 6},
	{"S_csLib_BAD_REPLY_BILAN", 4},
	{"S_csLib_BAD_RQST_ID", 3},
	{"S_csLib_INVALID_RQST_TYPE", 1},
	{"S_csLib_NOT_A_CLIENT", 5},
	{"S_csLib_NOT_A_SERV", 0},
	{"S_csLib_TOO_MANY_RQST_IDS", 2},
};

static H2_FAILED_STRUCT GCOM_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/posix/include/gcomLib.h */
	{"S_gcomLib_ERR_MBOX_MASK", 1},
	{"S_gcomLib_ERR_SEND_ID", 6},
	{"S_gcomLib_INVALID_BLOCK_MODE", 9},
	{"S_gcomLib_LETTER_NOT_OWNER", 8},
	{"S_gcomLib_MALLOC_FAILED", 11},
	{"S_gcomLib_NOT_A_LETTER", 2},
	{"S_gcomLib_REPLY_LETTER_TYPE", 10},
	{"S_gcomLib_SMALL_DATA_STR", 4},
	{"S_gcomLib_SMALL_LETTER", 3},
	{"S_gcomLib_TOO_MANY_LETTERS", 7},
	{"S_gcomLib_TOO_MANY_SENDS", 5},
};

static H2_FAILED_STRUCT H2DEV_LIB_TAB_FAIL[]= {
 /* From h2devLib.h */
	{"S_h2devLib_BAD_DEVICE_TYPE", 0},
	{"S_h2devLib_BAD_HOME_DIR", 6},
	{"S_h2devLib_BAD_PARAMETERS", 8},
	{"S_h2devLib_DUPLICATE_DEVICE_NAME", 1},
	{"S_h2devLib_FIND_DEVICE_TIMEOUT", 3},
	{"S_h2devLib_FULL", 7},
	{"S_h2devLib_NOT_FOUND", 9},
	{"S_h2devLib_NOT_INITIALIZED", 5},
	{"S_h2devLib_NOT_OWNER", 4},
	{"S_h2devLib_TOO_MANY_DEVICES", 2},
};

static H2_FAILED_STRUCT H2EVN_LIB_TAB_FAIL[]= {
 /* From h2evnLib.h */
	{"S_h2evnLib_BAD_TASK_ID", 0},
};

static H2_FAILED_STRUCT H2RNG_LIB_TAB_FAIL[]= {
 /* From h2rngLib.h */
	{"S_h2rngLib_BIG_BLOCK", 8},
	{"S_h2rngLib_ERR_SYNC", 5},
	{"S_h2rngLib_ILLEGAL_NBYTES", 0},
	{"S_h2rngLib_ILLEGAL_TYPE", 1},
	{"S_h2rngLib_NOT_A_BLOCK_RING", 4},
	{"S_h2rngLib_NOT_A_BYTE_RING", 3},
	{"S_h2rngLib_NOT_A_RING", 2},
	{"S_h2rngLib_SMALL_BLOCK", 7},
	{"S_h2rngLib_SMALL_BUF", 6},
};

static H2_FAILED_STRUCT H2SEM_LIB_TAB_FAIL[]= {
 /* From h2semLib.h */
	{"S_h2semLib_ALLOC_ERROR", 2},
	{"S_h2semLib_BAD_SEM_TYPE", 5},
	{"S_h2semLib_NOT_A_SEM", 3},
	{"S_h2semLib_TIMEOUT", 4},
	{"S_h2semLib_TOO_MANY_SEM", 1},
};

static H2_FAILED_STRUCT H2TIMER_LIB_TAB_FAIL[]= {
 /* From h2timerLib.h */
	{"S_h2timerLib_BAD_DELAY", 1},
	{"S_h2timerLib_BAD_PERIOD", 5},
	{"S_h2timerLib_NOT_STOPPED_TIMER", 4},
	{"S_h2timerLib_STOPPED_TIMER", 3},
	{"S_h2timerLib_TIMER_NOT_INIT", 0},
	{"S_h2timerLib_TOO_MUCH_TIMERS", 2},
};

static H2_FAILED_STRUCT INTER_CNTRL_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/inter/auto/interError.h */
	{"S_interCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_interCntrlTask_ACTIVITY_FAILED", 2},
	{"S_interCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_interCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_interCntrlTask_SYSTEM_ERROR", 6},
	{"S_interCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_interCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_interCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_interCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT INTER_INTER_EXEC_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/inter/auto/interError.h */
	{"S_interInterExecTask_NO_ACTION", 15},
	{"S_interInterExecTask_POSTER_ADDR_FAILED", 18},
	{"S_interInterExecTask_POSTER_INIT_FAILED", 17},
	{"S_interInterExecTask_POSTER_NOT_FOUND", 14},
	{"S_interInterExecTask_POSTER_READ_FAILED", 16},
	{"S_interInterExecTask_SPEAK_FAILED", 13},
};

static H2_FAILED_STRUCT INTER_MSG_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/inter/auto/interError.h */
	{"S_interMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT INTER_WRITE_REF_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/inter/auto/interError.h */
	{"S_interWriteRef_POSTER_US_NOT_FOUND", 12},
	{"S_interWriteRef_POTENTIAL_WELL", 10},
	{"S_interWriteRef_REPULSION_TIME_OUT", 11},
};

static H2_FAILED_STRUCT M2D_CMD_TAB_FAIL[]= {
 /* From auto/m2dError.h */
	{"S_m2dCmd_BAD_FILE", 21},
	{"S_m2dCmd_BAD_PARAMS", 18},
	{"S_m2dCmd_ERROR", 11},
	{"S_m2dCmd_INVALID_CALL", 14},
	{"S_m2dCmd_INVALID_GOAL_CONFIG", 17},
	{"S_m2dCmd_INVALID_PATH", 12},
	{"S_m2dCmd_INVALID_START_CONFIG", 16},
	{"S_m2dCmd_PATH_NOT_FOUND", 15},
	{"S_m2dCmd_POSTER_NOT_FOUND", 20},
	{"S_m2dCmd_POSTER_NOT_READABLE", 19},
	{"S_m2dCmd_ROBOT_NOT_CIRC", 13},
	{"S_m2dCmd_TRAJ_TOO_LONG", 10},
	{"S_m2dCmd_bad_planner_params", 22},
	{"S_m2dCmd_bad_rob_params", 23},
};

static H2_FAILED_STRUCT M2D_CNTRL_TASK_TAB_FAIL[]= {
 /* From auto/m2dError.h */
	{"S_m2dCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_m2dCntrlTask_ACTIVITY_FAILED", 2},
	{"S_m2dCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_m2dCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_m2dCntrlTask_SYSTEM_ERROR", 6},
	{"S_m2dCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_m2dCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_m2dCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_m2dCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT M2D_MSG_LIB_TAB_FAIL[]= {
 /* From auto/m2dError.h */
	{"S_m2dMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT MBOX_LIB_TAB_FAIL[]= {
 /* From mboxLib.h */
	{"S_mboxLib_BAD_IOCTL_CODE", 2},
	{"S_mboxLib_MBOX_CLOSED", 0},
	{"S_mboxLib_MBOX_FULL", 3},
	{"S_mboxLib_NAME_IN_USE", 4},
	{"S_mboxLib_NOT_OWNER", 1},
	{"S_mboxLib_SHORT_MESSAGE", 7},
	{"S_mboxLib_SMALL_BLOCK", 6},
	{"S_mboxLib_TOO_BIG", 5},
};

static H2_FAILED_STRUCT MEM_LIB_TAB_FAIL[]= {
 /* From memLib.h */
	{"S_memLib_NOT_ENOUGH_MEMORY", 1},
};

static H2_FAILED_STRUCT ND_CNTRL_TASK_TAB_FAIL[]= {
 /* From auto/ndError.h */
	{"S_ndCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_ndCntrlTask_ACTIVITY_FAILED", 2},
	{"S_ndCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_ndCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_ndCntrlTask_SYSTEM_ERROR", 6},
	{"S_ndCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_ndCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_ndCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_ndCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT ND_EXEC_TASK_TAB_FAIL[]= {
 /* From auto/ndError.h */
	{"S_ndExecTask_BAD_PARAMS", 10},
	{"S_ndExecTask_BAD_REF", 11},
	{"S_ndExecTask_BLOCKED", 16},
	{"S_ndExecTask_CANNOT_READ_LOCO_POSTER", 15},
	{"S_ndExecTask_CANNOT_READ_REF_POSTER", 13},
	{"S_ndExecTask_ND_ERROR", 14},
	{"S_ndExecTask_POSTER_NOT_FOUND", 18},
	{"S_ndExecTask_POSTER_READ_FAILED", 17},
	{"S_ndExecTask_TRACK_TIMEOUT", 12},
};

static H2_FAILED_STRUCT ND_MSG_LIB_TAB_FAIL[]= {
 /* From auto/ndError.h */
	{"S_ndMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT OBJ_LIB_TAB_FAIL[]= {
 /* From objLib.h */
	{"S_objLib_OBJ_ID_ERROR", 1},
	{"S_objLib_OBJ_TIMEOUT", 2},
};

static H2_FAILED_STRUCT PLATINE_CMD_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/platine/auto/platineError.h */
	{"S_platineCmdTask_DRIVER_NOT_INITIALIZED", 17},
	{"S_platineCmdTask_ERROR", 18},
	{"S_platineCmdTask_PT_ILLEGAL_ACCEL", 14},
	{"S_platineCmdTask_PT_ILLEGAL_COMMAND", 23},
	{"S_platineCmdTask_PT_NO_ERR", 22},
	{"S_platineCmdTask_PT_OUT_OF_RANGE", 16},
	{"S_platineCmdTask_PT_SMALL_PAN_VALUE", 12},
	{"S_platineCmdTask_PT_SMALL_TILT_VALUE", 11},
	{"S_platineCmdTask_PT_STOP_ENDS", 15},
	{"S_platineCmdTask_PT_SYS_ERR", 13},
	{"S_platineCmdTask_PT_UNKNOWN_ERR", 21},
	{"S_platineCmdTask_UNVALID_PARAMS", 19},
};

static H2_FAILED_STRUCT PLATINE_CNTRL_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/platine/auto/platineError.h */
	{"S_platineCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_platineCntrlTask_ACTIVITY_FAILED", 2},
	{"S_platineCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_platineCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_platineCntrlTask_SYSTEM_ERROR", 6},
	{"S_platineCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_platineCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_platineCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_platineCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT PLATINE_GET_POS_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/platine/auto/platineError.h */
	{"S_platineGetPosTask_INIT_FAILED", 20},
	{"S_platineGetPosTask_POSTER_NOT_FOUND", 10},
};

static H2_FAILED_STRUCT PLATINE_MSG_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/platine/auto/platineError.h */
	{"S_platineMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT POSTER_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/posix/include/posterLib.h */
	{"S_posterLib_BAD_IOCTL_CODE", 4},
	{"S_posterLib_BAD_OP", 5},
	{"S_posterLib_DUPLICATE_POSTER", 10},
	{"S_posterLib_EMPTY_POSTER", 3},
	{"S_posterLib_INVALID_PATH", 11},
	{"S_posterLib_MALLOC_ERROR", 12},
	{"S_posterLib_NOT_OWNER", 1},
	{"S_posterLib_POSTER_CLOSED", 0},
	{"S_posterLib_SEMGET_ERROR", 15},
	{"S_posterLib_SEMOP_ERROR", 16},
	{"S_posterLib_SHMAT_ERROR", 14},
	{"S_posterLib_SHMGET_ERROR", 13},
};

static H2_FAILED_STRUCT REMOTE_POSTER_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/posix/include/remotePosterLib.h */
	{"S_remotePosterLib_BAD_ALLOC", 11},
	{"S_remotePosterLib_BAD_IOCTL_CODE", 4},
	{"S_remotePosterLib_BAD_OP", 5},
	{"S_remotePosterLib_BAD_PARAMS", 13},
	{"S_remotePosterLib_BAD_RPC", 10},
	{"S_remotePosterLib_CORRUPT_DATA", 12},
	{"S_remotePosterLib_EMPTY_POSTER", 3},
	{"S_remotePosterLib_ERR_TIME_READ", 2},
	{"S_remotePosterLib_NOT_OWNER", 1},
	{"S_remotePosterLib_POSTER_CLOSED", 0},
	{"S_remotePosterLib_POSTER_HOST_NOT_DEFINED", 14},
};

static H2_FAILED_STRUCT SEGLOC_CMD_TASK_TAB_FAIL[]= {
 /* From /home/matthieu/robots/nomadic/modules/segloc/auto/seglocError.h */
	{"S_seglocCmdTask_BIG_JUMP", 22},
	{"S_seglocCmdTask_ERROR", 11},
	{"S_seglocCmdTask_FAILED", 17},
	{"S_seglocCmdTask_FILE_NOT_FOUND", 16},
	{"S_seglocCmdTask_LOC_FAILED", 21},
	{"S_seglocCmdTask_PARTIAL_LOC", 19},
	{"S_seglocCmdTask_POSTER_NOT_FOUND", 14},
	{"S_seglocCmdTask_SEG_FAILED", 20},
	{"S_seglocCmdTask_SEG_NOT_FOUND", 12},
	{"S_seglocCmdTask_SERVER_FAILED", 15},
	{"S_seglocCmdTask_SEVERAL_SOLUTIONS", 18},
	{"S_seglocCmdTask_TOO_MANY_SEGS_IN_MAP", 13},
};

static H2_FAILED_STRUCT SEGLOC_CNTRL_TASK_TAB_FAIL[]= {
 /* From /home/matthieu/robots/nomadic/modules/segloc/auto/seglocError.h */
	{"S_seglocCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_seglocCntrlTask_ACTIVITY_FAILED", 2},
	{"S_seglocCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_seglocCntrlTask_BAD_PARAMS", 10},
	{"S_seglocCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_seglocCntrlTask_SYSTEM_ERROR", 6},
	{"S_seglocCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_seglocCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_seglocCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_seglocCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT SEGLOC_MSG_LIB_TAB_FAIL[]= {
 /* From /home/matthieu/robots/nomadic/modules/segloc/auto/seglocError.h */
	{"S_seglocMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT SEM_LIB_TAB_FAIL[]= {
 /* From semLib.h */
	{"S_semLib_ALLOC_ERROR", 2},
	{"S_semLib_NOT_A_SEM", 3},
	{"S_semLib_TIMEOUT", 4},
	{"S_semLib_TOO_MANY_SEM", 1},
};

static H2_FAILED_STRUCT SICK_CNTRL_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/sick/auto/sickError.h */
	{"S_sickCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_sickCntrlTask_ACTIVITY_FAILED", 2},
	{"S_sickCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_sickCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_sickCntrlTask_SYSTEM_ERROR", 6},
	{"S_sickCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_sickCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_sickCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_sickCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT SICK_MSG_LIB_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/sick/auto/sickError.h */
	{"S_sickMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT SICK_SCAN_TASK_TAB_FAIL[]= {
 /* From /usr/local/robots/nomadic/modules/sick/auto/sickError.h */
	{"S_sickScanTask_bad_tram", 14},
	{"S_sickScanTask_cannot_find_baud_rate", 15},
	{"S_sickScanTask_fatal_error", 17},
	{"S_sickScanTask_isnot_initialized", 10},
	{"S_sickScanTask_reset_error", 11},
	{"S_sickScanTask_serial_input_error", 13},
	{"S_sickScanTask_serial_output_error", 12},
	{"S_sickScanTask_time_out", 16},
};

static H2_FAILED_STRUCT SM_OBJ_LIB_TAB_FAIL[]= {
 /* From smObjLib.h */
	{"S_smObjLib_SHMAT_ERROR", 11},
	{"S_smObjLib_SHMGET_ERROR", 10},
};

static H2_FAILED_STRUCT STAT_CNTRL_TASK_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/stat/auto/statError.h */
	{"S_statCntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_statCntrlTask_ACTIVITY_FAILED", 2},
	{"S_statCntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_statCntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_statCntrlTask_SYSTEM_ERROR", 6},
	{"S_statCntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_statCntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_statCntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_statCntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT STAT_MSG_LIB_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/stat/auto/statError.h */
	{"S_statMsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT STATSTAT_EXEC_TASK_TAB_FAIL[]= {
 /* From /home/bmorisse/robots/nomadic/modules/stat/auto/statError.h */
	{"S_statstatExecTask_FILE_NOT_FOUND", 11},
	{"S_statstatExecTask_POSTER_READ_FAILED", 12},
	{"S_statstatExecTask_WRONG_NB_ARGS", 10},
};

static H2_FAILED_STRUCT SYM_LIB_TAB_FAIL[]= {
 /* From symLib.h */
	{"S_symLib_SYMBOL_NOT_FOUND", 1},
};

static H2_FAILED_STRUCT XR4000_CNTRL_TASK_TAB_FAIL[]= {
 /* From auto/xr4000Error.h */
	{"S_xr4000CntrlTask_ACTIVITY_ALREADY_ENDED", 7},
	{"S_xr4000CntrlTask_ACTIVITY_FAILED", 2},
	{"S_xr4000CntrlTask_ACTIVITY_INTERRUPTED", 0},
	{"S_xr4000CntrlTask_BAD_CMD_DATA", 13},
	{"S_xr4000CntrlTask_BAD_REF_DATA", 11},
	{"S_xr4000CntrlTask_BAD_SERVO_MODE", 12},
	{"S_xr4000CntrlTask_FORBIDDEN_ACTIVITY_TRANSITION", 5},
	{"S_xr4000CntrlTask_SYSTEM_ERROR", 6},
	{"S_xr4000CntrlTask_TOO_MANY_ACTIVITIES", 1},
	{"S_xr4000CntrlTask_TRACKING_ON", 10},
	{"S_xr4000CntrlTask_UNKNOWN_ACTIVITY", 4},
	{"S_xr4000CntrlTask_WAIT_ABORT_ZOMBIE_ACTIVITY", 3},
	{"S_xr4000CntrlTask_WAIT_INIT_RQST", 8},
};

static H2_FAILED_STRUCT XR4000_EXEC_TASK_TAB_FAIL[]= {
 /* From auto/xr4000Error.h */
	{"S_xr4000ExecTask_AXES_NOT_READY", 18},
	{"S_xr4000ExecTask_CONNECTION_FAILED", 22},
	{"S_xr4000ExecTask_ESTOP_DOWN", 25},
	{"S_xr4000ExecTask_INVALID_ARGUMENT", 27},
	{"S_xr4000ExecTask_JOYSTICK_IN_USE", 26},
	{"S_xr4000ExecTask_MOTION_ERROR", 24},
	{"S_xr4000ExecTask_OUT_OF_MEMORY", 21},
	{"S_xr4000ExecTask_POSTER_NOT_FOUND", 17},
	{"S_xr4000ExecTask_ROBOT_NOT_FOUND", 23},
	{"S_xr4000ExecTask_UNINITIALIZED", 19},
	{"S_xr4000ExecTask_UNKNOWN_AXIS_STATUS", 28},
	{"S_xr4000ExecTask_UNKNOWN_ERROR", 20},
};

static H2_FAILED_STRUCT XR4000_MSG_LIB_TAB_FAIL[]= {
 /* From auto/xr4000Error.h */
	{"S_xr4000MsgLib_BAD_BLOCK_TYPE", 0},
};

static H2_FAILED_STRUCT XR4000_PUMP_TASK_TAB_FAIL[]= {
 /* From auto/xr4000Error.h */
	{"S_xr4000PumpTask_BAD_REF", 16},
	{"S_xr4000PumpTask_CMD_STOP_TRACK", 15},
	{"S_xr4000PumpTask_POSTER_NOT_UPDATED", 14},
};


/*
 * Array of the sources of errors
 * (source name, source number, array of errors, number of errors)
 */

static H2_SOURCE_FAILED_STRUCT H2_SOURCE_TAB_FAIL[] = {
 /* From /home/bmorisse/robots/nomadic/modules/UGrid-nomadic/auto/UGridError.h */
	{"M_UGridCntrlTask", 9010, _U_GRID_CNTRL_TASK_TAB_FAIL, 9},
	{"M_UGridMatriceFixeTask", 9013, _U_GRID_MATRICE_FIXE_TASK_TAB_FAIL, 6},
	{"M_UGridMsgLib", 9011, _U_GRID_MSG_LIB_TAB_FAIL, 1},
	{"M_UGridPosterLib", 9012, NULL, 0},
 /* From /usr/local/robots/nomadic/modules/band/auto/bandError.h */
	{"M_bandCntrlTask", 3600, BAND_CNTRL_TASK_TAB_FAIL, 9},
	{"M_bandExecTask", 3603, BAND_EXEC_TASK_TAB_FAIL, 8},
 /* From /usr/local/robots/nomadic/band/band.h */
	{"M_bandLib", 3605, BAND_LIB_TAB_FAIL, 1},
 /* From /usr/local/robots/nomadic/modules/band/auto/bandError.h */
	{"M_bandMsgLib", 3601, BAND_MSG_LIB_TAB_FAIL, 1},
	{"M_bandPosterLib", 3602, NULL, 0},
 /* From commonStructLib.h */
	{"M_commonStructLib", 506, COMMON_STRUCT_LIB_TAB_FAIL, 1},
 /* From csLib.h */
	{"M_csLib", 512, CS_LIB_TAB_FAIL, 8},
 /* From /usr/local/robots/posix/include/gcomLib.h */
	{"M_gcomLib", 511, GCOM_LIB_TAB_FAIL, 11},
 /* From h2devLib.h */
	{"M_h2devLib", 505, H2DEV_LIB_TAB_FAIL, 10},
 /* From h2evnLib.h */
	{"M_h2evnLib", 507, H2EVN_LIB_TAB_FAIL, 1},
 /* From h2rngLib.h */
	{"M_h2rngLib", 501, H2RNG_LIB_TAB_FAIL, 9},
 /* From h2semLib.h */
	{"M_h2semLib", 503, H2SEM_LIB_TAB_FAIL, 5},
 /* From h2timerLib.h */
	{"M_h2timerLib", 504, H2TIMER_LIB_TAB_FAIL, 6},
 /* From /usr/local/robots/nomadic/modules/inter/auto/interError.h */
	{"M_interCntrlTask", 9000, INTER_CNTRL_TASK_TAB_FAIL, 9},
	{"M_interInterExecTask", 9003, INTER_INTER_EXEC_TASK_TAB_FAIL, 6},
	{"M_interMsgLib", 9001, INTER_MSG_LIB_TAB_FAIL, 1},
	{"M_interPosterLib", 9002, NULL, 0},
	{"M_interWriteRef", 9004, INTER_WRITE_REF_TAB_FAIL, 3},
 /* From auto/m2dError.h */
	{"M_m2dCmd", 3613, M2D_CMD_TAB_FAIL, 14},
	{"M_m2dCntrlTask", 3610, M2D_CNTRL_TASK_TAB_FAIL, 9},
	{"M_m2dMsgLib", 3611, M2D_MSG_LIB_TAB_FAIL, 1},
	{"M_m2dPosterLib", 3612, NULL, 0},
 /* From mboxLib.h */
	{"M_mboxLib", 508, MBOX_LIB_TAB_FAIL, 8},
 /* From memLib.h */
	{"M_memLib", 17, MEM_LIB_TAB_FAIL, 1},
 /* From auto/ndError.h */
	{"M_ndCntrlTask", 9030, ND_CNTRL_TASK_TAB_FAIL, 9},
	{"M_ndExecTask", 9033, ND_EXEC_TASK_TAB_FAIL, 9},
	{"M_ndMsgLib", 9031, ND_MSG_LIB_TAB_FAIL, 1},
	{"M_ndPosterLib", 9032, NULL, 0},
 /* From objLib.h */
	{"M_objLib", 61, OBJ_LIB_TAB_FAIL, 2},
 /* From /usr/local/robots/nomadic/modules/platine/auto/platineError.h */
	{"M_platineCmdTask", 3033, PLATINE_CMD_TASK_TAB_FAIL, 12},
	{"M_platineCntrlTask", 3030, PLATINE_CNTRL_TASK_TAB_FAIL, 9},
	{"M_platineGetPosTask", 3034, PLATINE_GET_POS_TASK_TAB_FAIL, 2},
	{"M_platineMsgLib", 3031, PLATINE_MSG_LIB_TAB_FAIL, 1},
	{"M_platinePosterLib", 3032, NULL, 0},
 /* From /usr/local/robots/posix/include/posterLib.h */
	{"M_posterLib", 510, POSTER_LIB_TAB_FAIL, 12},
 /* From /usr/local/robots/posix/include/remotePosterLib.h */
	{"M_remotePosterLib", 516, REMOTE_POSTER_LIB_TAB_FAIL, 11},
 /* From /home/matthieu/robots/nomadic/modules/segloc/auto/seglocError.h */
	{"M_seglocCmdTask", 3333, SEGLOC_CMD_TASK_TAB_FAIL, 12},
	{"M_seglocCntrlTask", 3330, SEGLOC_CNTRL_TASK_TAB_FAIL, 10},
	{"M_seglocMsgLib", 3331, SEGLOC_MSG_LIB_TAB_FAIL, 1},
	{"M_seglocPosterLib", 3332, NULL, 0},
 /* From semLib.h */
	{"M_semLib", 22, SEM_LIB_TAB_FAIL, 4},
 /* From /usr/local/robots/nomadic/modules/sick/auto/sickError.h */
	{"M_sickCntrlTask", 3500, SICK_CNTRL_TASK_TAB_FAIL, 9},
	{"M_sickMsgLib", 3501, SICK_MSG_LIB_TAB_FAIL, 1},
	{"M_sickPosterLib", 3502, NULL, 0},
	{"M_sickScanTask", 3503, SICK_SCAN_TASK_TAB_FAIL, 8},
 /* From smObjLib.h */
	{"M_smObjLib", 72, SM_OBJ_LIB_TAB_FAIL, 2},
 /* From /home/bmorisse/robots/nomadic/modules/stat/auto/statError.h */
	{"M_statCntrlTask", 5023, STAT_CNTRL_TASK_TAB_FAIL, 9},
	{"M_statMsgLib", 5024, STAT_MSG_LIB_TAB_FAIL, 1},
	{"M_statPosterLib", 5025, NULL, 0},
	{"M_statstatExecTask", 5026, STATSTAT_EXEC_TASK_TAB_FAIL, 3},
 /* From symLib.h */
	{"M_symLib", 28, SYM_LIB_TAB_FAIL, 1},
 /* From tickLib.h */
	{"M_tickLib", 60, NULL, 0},
 /* From wdLib.h */
	{"M_wdLib", 34, NULL, 0},
 /* From auto/xr4000Error.h */
	{"M_xr4000CntrlTask", 3620, XR4000_CNTRL_TASK_TAB_FAIL, 13},
	{"M_xr4000ExecTask", 3624, XR4000_EXEC_TASK_TAB_FAIL, 12},
	{"M_xr4000MsgLib", 3621, XR4000_MSG_LIB_TAB_FAIL, 1},
	{"M_xr4000PosterLib", 3622, NULL, 0},
	{"M_xr4000PumpTask", 3623, XR4000_PUMP_TASK_TAB_FAIL, 3},
};

